/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.clubsociosaepda.view.gui;

import com.mycompany.clubsociosaepda.controller.GestorClub;
import com.mycompany.clubsociosaepda.exception.AEDPAException;
import com.mycompany.clubsociosaepda.model.Activitat;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan-
 */
public class MostrarActivitatsJDialog extends javax.swing.JDialog {
    private GestorClub gestor;

    /**
     * Creates new form MostrarActivitatsJDialog
     * @param parent
     * @param gestor
     * @param modal
     */
    public MostrarActivitatsJDialog(
            java.awt.Frame parent,
            boolean modal,
            GestorClub gestor) {
            super(parent, modal);
            this.gestor = gestor;
            initComponents();
            this.setLocationRelativeTo(null);
            cargarTabla();
    }

    private void cargarTabla() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tablaActivitats.getModel();
            modelo.setRowCount(0);
            List<Activitat> activitats = gestor.mostrarActivitats(0);
            for (Activitat a : activitats) {
                Object[] fila = new Object[4];
                fila[0] = a.getIdActivitat();
                fila[1] = a.getNom();
                fila[2] = a.getClass().getSimpleName();
                fila[3] = a.getData();
                modelo.addRow(fila);
            }
        } catch (AEDPAException | SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No s'han pogut mostrar les activitats:\n"
                    + e.getMessage(),
                    "Error Activitats",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaActivitats = new javax.swing.JTable();
        botonEnrere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaActivitats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Tipus", "Data"
            }
        ));
        jScrollPane1.setViewportView(tablaActivitats);

        botonEnrere.setText("Enrere");
        botonEnrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnrereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(botonEnrere)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEnrere)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnrereActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonEnrereActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnrere;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaActivitats;
    // End of variables declaration//GEN-END:variables
}
