/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.clubsociosaepda.view.gui;

import com.mycompany.clubsociosaepda.controller.GestorClub;
import com.mycompany.clubsociosaepda.model.Balda;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author juan-
 */
public class MostrarBaldesJDialog extends javax.swing.JDialog {
    private GestorClub gestor;

    /**
     * Creates new form MostrarBaldesJDialog
     * @param parent
     * @param modal
     * @param gestor
     */
    public MostrarBaldesJDialog(
        java.awt.Frame parent,
        boolean modal,
        GestorClub gestor) {
        super(parent, modal);
        this.gestor = gestor;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
    }

    private void cargarTabla() {
        try {
            DefaultTableModel modelo =(DefaultTableModel)tablaBaldes.getModel();
            modelo.setRowCount(0);
            List<String> baldes = gestor.mostrarBaldas();
            for (String b : baldes) {
                Object[] fila = new Object[1];
                fila[0] = b;
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No s'han pogut mostrar les baldes:\n"
                    + e.getMessage(),
                    "Error Baldes",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonEnrere = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBaldes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonEnrere.setText("Enrere");
        botonEnrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnrereActionPerformed(evt);
            }
        });

        tablaBaldes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Informació Balda"
            }
        ));
        jScrollPane1.setViewportView(tablaBaldes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(botonEnrere))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEnrere)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnrereActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonEnrereActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnrere;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBaldes;
    // End of variables declaration//GEN-END:variables
}
