/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clubsociosaepda.view.gui;

import com.mycompany.clubsociosaepda.controller.GestorClub;
import com.mycompany.clubsociosaepda.exception.AEDPAException;
import com.mycompany.clubsociosaepda.exception.PersistenciaException;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author josea
 */
public class Principal extends javax.swing.JFrame {

    private GestorClub gestor;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            gestor = new GestorClub();
        } catch (AEDPAException | PersistenciaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        jMenu2.setText("Usuaris");

        jMenuItem1.setText("Alta Usuari");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Mostrar Usuari");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Eliminar Usuari");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Fer Soci");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Finalitzar Membresia");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Inscriure Usuari");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenu1.add(jMenu2);

        jMenu3.setText("Activitats");

        jMenuItem7.setText("Alta Activitat");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Eliminar Activitat");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Mostrar Activitats");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Mostrar Activitat Concreta");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenu1.add(jMenu3);

        jMenu4.setText("Baldas");

        jMenuItem11.setText("Alta Balda");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Modificar Balda");
        jMenu4.add(jMenuItem12);

        jMenuItem13.setText("Asignar Balda");
        jMenu4.add(jMenuItem13);

        jMenuItem14.setText("Alliberar balda");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuItem15.setText("Mostrar Baldes");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem16.setText("Disponibilitat baldes");
        jMenu4.add(jMenuItem16);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AltaUsuariJDialog dialog
                = new AltaUsuariJDialog(
                        this,
                        true,
                        gestor
                );
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        AltaActivitatJDialog dialog =
                new AltaActivitatJDialog(
                        this,
                        true,
                        gestor
                );
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        BorrarUsuari borrarDialogC
                = new BorrarUsuari(this, true, gestor);
        borrarDialogC.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            String dni = JOptionPane.showInputDialog( this, "Introdueix el DNI del usuari:"
                    );
            if (dni == null || dni.isBlank()) {
                return;
            }
            String info
                    = gestor.mostrarUsuari(dni).toString();
            JOptionPane.showMessageDialog( this, info, "Informació Usuari", JOptionPane.INFORMATION_MESSAGE
            );
        } catch (AEDPAException | HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "No s'ha pogut mostrar l'usuari:\n" + e.getMessage(), "Error Usuari", JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
            try {
            String dni = JOptionPane.showInputDialog(
                            this,
                            "DNI del usuari:"
                    );
            String mesosText = JOptionPane.showInputDialog(
                            this,
                            "Mesos de membresia:"
                    );
            int mesos = Integer.parseInt(mesosText);
            gestor.ferSoci(dni, mesos); JOptionPane.showMessageDialog(
                    this,
                    "Usuari convertit en soci correctament",
                    "Soci Registrat",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } catch (AEDPAException | HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "No s'ha pogut convertir l'usuari en soci:\n"
                    + e.getMessage(),
                    "Error Soci",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
            try {
            String dni = JOptionPane.showInputDialog(
                            this,
                            "DNI del usuari:"
                    );
            gestor.finalitzarMembresia(dni); JOptionPane.showMessageDialog(
                    this,
                    "Membresia finalitzada correctament",
                    "Baixa Soci",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } catch (AEDPAException | HeadlessException | SQLException e) { JOptionPane.showMessageDialog(
                    this,
                    "No s'ha pogut finalitzar la membresia:\n"
                    + e.getMessage(),
                    "Error Membresia",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            String idText = JOptionPane.showInputDialog(
                            this,
                            "ID de l'activitat:"
                    );
            int id = Integer.parseInt(idText);
            String dni =
                    JOptionPane.showInputDialog(
                            this,
                            "DNI del usuari:"
                    );
            gestor.inscriureActivitat(id, dni); JOptionPane.showMessageDialog(
                    this,
                    "Usuari inscrit correctament",
                    "Inscripció Activitat",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } catch (AEDPAException | PersistenciaException | HeadlessException | NumberFormatException | SQLException e) { JOptionPane.showMessageDialog(
                    this,
                    "No s'ha pogut inscriure l'usuari:\n"
                    + e.getMessage(),
                    "Error Inscripció",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
            try { String idText = JOptionPane.showInputDialog(
                                this,
                                "ID de l'activitat:"
                        );
                int id = Integer.parseInt(idText);
                gestor.eliminarActivitat(id);
                JOptionPane.showMessageDialog(
                        this,
                        "Activitat eliminada correctament",
                        "Eliminar Activitat",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } catch (AEDPAException | HeadlessException | NumberFormatException | SQLException e) { JOptionPane.showMessageDialog(
                        this,
                        "No s'ha pogut eliminar l'activitat:\n"
                        + e.getMessage(),
                        "Error Activitat",
                        JOptionPane.ERROR_MESSAGE
           );
       }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
                MostrarActivitatsJDialog dialog = new MostrarActivitatsJDialog(
                    this,
                    true,
                    gestor
            );
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        try {
                String nom =
                        JOptionPane.showInputDialog(
                                this,
                                "Nom de l'activitat:"
                        );
                if (nom == null || nom.isBlank()) {
                    return;
                }
                String info = gestor.mostrarActivitatEspecifica(nom); JOptionPane.showMessageDialog(
                        this,
                        info,
                        "Informació Activitat",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } catch (AEDPAException | HeadlessException | SQLException e) {JOptionPane.showMessageDialog(
                        this,
                        "No s'ha pogut mostrar l'activitat:\n"
                        + e.getMessage(),
                        "Error Activitat",
                        JOptionPane.ERROR_MESSAGE
                );
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
            MostrarBaldesJDialog dialog =
            new MostrarBaldesJDialog(
                    this,
                    true,
                    gestor
            );
            dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
